---
- name: Istall WordPress Apache
  hosts: '{{ HOST }}'
  become: yes

  vars:
    db_name: wordpress
    db_user: wp_user
    db_password: wp_pass
    wp_url: https://wordpress.org/latest.tar.gz
    wp_dir: /var/www/html

  tasks:
    - name: Install Packages
      apt:
        name:
          - python3-pymysql
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - libapache2-mod-php
          - wget
        update_cache: yes

    - name: start apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create DB
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create user MySQL
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    
    - name: download & unpack WordPress
      unarchive:
        src: "{{ wp_url }}"
        dest: "{{ wp_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: change rules for dir
      file:
        path: "{{ wp_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Remove default Apache index.html
      file:
        path: /var/www/html/index.html
        state: absent      

    - name: restart apache2
      service:
        name: apache2
        state: restarted

